### ISSUE TITLE
Could not install xformers and the material estimation is worse than your paper

### ISSUE THREAD

**Issue by ge79puv** [Peter-Kocsis/IntrinsicImageDiffusion#15]
Hey there,

I tried to install xformers to improve the performance. However, xformers requires python > 3.9, but in environment.yml, the version is 3.8.16. Could I upgrade the python version?

Btw, the results of material estimation is different from that in your paper. Could you tell me the possible influencing factors and method to further improve?
![albedo_pred_](https://github.com/user-attachments/assets/fcb92d91-8989-4231-9609-7b8994b366c6)

Best regards

**Comment by ge79puv** [comment]
Or are there some key parameters (maybe in *yaml files) that can help improve the evaluation results and achieve the same results as in the paper? Thanks for your help in advance.

**Comment by Peter-Kocsis** [comment]
Hi, yes, python 3.9 should work well; thanks for pointing it out! The prediction quality depends on the number of samples used during the sampling. In the paper, we used 10 samples, but you can try with more. An additional hyperparameter that can help is using DDPM sampling instead of DDIM. DDIM improves the runtime on the cost of quality. Furthermore, in the paper sometimes we show results evaluated on 240x320 resolution to be fair with the baselines.
